"use client";
import { useState } from "react";

type Page = "home" | "work" | "places" | "interests" | "socials";
const pages: Page[] = ["home", "work", "places", "interests", "socials"];
const socialLinks = [
  { name:"LinkedIn", icon:"linkedin", note:"Work, writing & professional updates", href:"https://linkedin.com/in/akshaymerchant" },
  { name:"GitHub", icon:"github", note:"Code, projects & experiments", href:"https://github.com/merchantakshay" },
  { name:"Download CV", icon:"document", note:"Experience, education & expertise", href:"https://github.com/merchantakshay/merchantakshay.github.io/blob/main/AkshayMerchantResume(DE_2).pdf" },
  { name:"Instagram", icon:"instagram", note:"Life outside the résumé", href:"https://www.instagram.com/akshaymerchant/" },
];
const cityMarks: Record<string,string> = {mumbai:"☀",chicago:"≋",newyork:"▥",dc:"★",seattle:"▲",luxembourg:"♜"};
const experienceHighlights = [
  { n:"01", title:"Build", copy:"Designed cloud data platforms, automated pipelines and delivery-health systems across Engineering Services and Alexa.", impact:"$120K saved · 10K+ hours returned" },
  { n:"02", title:"Scale", copy:"Turned analytics and data quality into shared capabilities used across global, cross-functional teams.", impact:"3× adoption · 99% fewer defects" },
  { n:"03", title:"Lead", copy:"Shaped roadmaps, architecture decisions and technical standards while partnering directly with senior leaders.", impact:"20+ teams · 75+ interviews" },
];
const places = [
  { id:"mumbai", city:"Mumbai", years:"Chapter 01", x:67, y:61, blurb:"I grew up in Bandra, often called the “Queen of the Suburbs.” It is a neighbourhood where heritage and modern life sit comfortably side by side—from Portuguese-era churches and colonial bungalows to lively streets and seafront promenades overlooking the Arabian Sea. Much of my childhood was spent playing sports. I learned swimming, skating and table tennis, played countless games of football and cricket with friends, and represented my school in cricket. When I wasn’t playing, I was usually reading. I loved visiting bookstores and rarely missed an opportunity to pick up a new book. Bandra gave me a childhood filled with curiosity, competition and community—and it remains the place that feels most like home." },
  { id:"chicago", city:"Chicago", years:"Chapter 02", x:24, y:35, blurb:"Chicago, often called the “Windy City,” was where I moved for graduate school—and where I quickly discovered that the name was very well earned. Between classes, I made new friends and explored the city one neighbourhood at a time. I loved walking along the Magnificent Mile, wondering when I would finally be able to afford a proper shopping spree, cycling by Navy Pier, going on Costco runs with friends and eating more deep-dish pizza than was probably necessary. There were fun moments, strange moments and a few slightly scary ones, but never a shortage of stories. I arrived knowing very few people and left with great friends, plenty of memories and, thankfully, a degree." },
  { id:"newyork", city:"New York", years:"Chapter 03", x:30.5, y:39, blurb:"New York, famously known as the “City That Never Sleeps,” was where I moved while job hunting, convinced that finding a job there would be easier if I actually lived there. I spent just two months in the city—or, more specifically, in Bay Ridge—but they remain some of my favourite months. I loved walking along the pier at night with the Manhattan skyline in the distance, taking the ferry, cycling through Central Park and, like every proper tourist, petting the Charging Bull on Wall Street. I also made it my mission to find the perfect New York slice, with Artichoke becoming the clear favourite. It was a short stay, but one packed with memorable views, excellent pizza and plenty of reasons to keep exploring." },
  { id:"dc", city:"Washington DC", years:"Chapter 04", x:29, y:43, blurb:"Washington, DC—best known as the nation’s capital—has always been my favourite city, although I have never been able to pinpoint exactly why. Maybe it was the allure of the capital, the excitement of starting my first job or simply how much of the city I managed to explore. I played football and kickball on the National Mall, made some great friends and then became even better friends over drinks afterwards. DC was also where I first discovered Lime scooters, and riding through the streets while taking in the monuments and views remains one of my favourite ways to experience a city. I loved visiting Georgetown for its streets, its famous cupcakes and, of course, a trip down the Exorcist Steps. I spent plenty of time exploring the museums too, with the International Spy Museum easily taking first place. I took visiting friends there whenever I could—and I still have a few trinkets from the gift shop to prove it." },
  { id:"seattle", city:"Seattle", years:"Chapter 05", x:15, y:32, blurb:"Seattle, famously known as the “Emerald City,” became home just before COVID arrived—which was not exactly ideal timing for exploring a new place. Still, I managed to collect plenty of good memories. I joined my first sports club, learned to play squash and went running along the Seattle waterfront. I bought my first phone entirely with my own savings, which felt like a major milestone at the time. When COVID cancelled every flight back, my mom found herself unexpectedly stuck with me, so we made the best of it with regular Indian-food runs around the city. I also took a seaplane ride, tried glassblowing and went on some of the most beautiful hikes I had ever seen. Seattle may have begun with unfortunate timing, but between the mountains, water, new hobbies and an unexpectedly extended visit from my mom, it became a chapter with no shortage of memorable moments." },
  { id:"luxembourg", city:"Luxembourg", years:"Chapter 06", x:50, y:35, blurb:"Luxembourg, one of Europe’s smallest countries, was where I moved to experience life on the continent—and it has turned into a much bigger adventure than I expected. The beginning was challenging but certainly eventful: registering at the commune, finding an apartment and navigating a new country in a language I did not yet speak. Once the paperwork settled, the fun really began. Over the years, I have made new friends, travelled widely across Europe and become fitter than ever, all while enjoying Luxembourg’s wonderfully varied calendar. There have been evenings at the Schueberfouer, cheering at the Duck Race, free concerts during Duke's Day celebrations and plenty of Christmas markets. I have explored lakes, castles and picturesque towns—often without paying a cent to get there, thanks to the country’s free public transport. Luxembourg may be small, but it has given me an impressively long list of places to visit, traditions to enjoy and stories to tell." },
];
const capabilities = [
  { n:"01", over:"Build", title:"Data systems", copy:"Python · SQL · Airflow · ETL / ELT · Data modeling · Automation" },
  { n:"02", over:"Operate", title:"Cloud platforms", copy:"AWS · S3 · RDS · Redshift · DMS · CloudWatch · CI/CD" },
  { n:"03", over:"Understand", title:"Analytics", copy:"Power BI · Tableau · QuickSight · Metabase · Reporting" },
  { n:"04", over:"Trust", title:"Quality & governance", copy:"Validation · Observability · Ownership · SLA monitoring" },
  { n:"05", over:"Shape", title:"Data strategy", copy:"Architecture · Roadmaps · Readiness · Platform adoption" },
  { n:"06", over:"Lead", title:"Technical leadership", copy:"Discovery · Stakeholders · Standards · Training" },
];
const Arrow = () => <span aria-hidden="true">↗</span>;
const KpiIcon = ({name}:{name:"people"|"savings"|"time"|"quality"}) => {
  if(name==="people") return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3.5 19c.3-3.5 2.2-5 5.5-5s5.2 1.5 5.5 5M16 6.5a2.5 2.5 0 0 1 0 5M17 14c2.2.4 3.3 2 3.5 4.5"/></svg>;
  if(name==="savings") return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5"/><path d="M15.5 8.5c-.7-.7-1.8-1-3-1-1.7 0-3 .8-3 2s1 1.8 3 2.3 3 1 3 2.3-1.2 2.2-3.2 2.2c-1.2 0-2.4-.4-3.2-1.2M12 5.5v13"/></svg>;
  if(name==="time") return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3.5 2"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 19 6v5.5c0 4.2-2.7 7.5-7 9.5-4.3-2-7-5.3-7-9.5V6z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg>;
};
const SocialIcon = ({name}:{name:string}) => {
  if(name==="email") return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m4 7 8 6 8-6"/></svg>;
  if(name==="linkedin") return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 10v7M8 7.5v.01M12 17v-7m0 3c.6-2 4-2.2 4 1v3"/></svg>;
  if(name==="github") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 21v-4a4 4 0 0 0-1-3c3 0 6-1.5 6-6a5 5 0 0 0-1.5-3.5A5 5 0 0 0 18.4 1S17.2.6 15 2.5a13 13 0 0 0-6 0C6.8.6 5.6 1 5.6 1a5 5 0 0 0-.1 3.5A5 5 0 0 0 4 8c0 4.5 3 6 6 6a4 4 0 0 0-1 3v4M9 18c-3 .9-3-1.5-4-2"/></svg>;
  if(name==="instagram") return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".7" className="icon-fill"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></svg>;
};

export default function Home() {
  const [page,setPage] = useState<Page>("home");
  const [place,setPlace] = useState("luxembourg");
  const goTo = (next:Page) => { setPage(next); window.scrollTo({top:0,behavior:"auto"}); };
  const selected = places.find(p=>p.id===place)!;
  return <main className="site">
    <div className="canvas">
      <header className="topbar"><button className="monogram" onClick={()=>goTo("home")}>AM<span>.</span></button><nav>{pages.map(p=><button key={p} className={page===p?"active":""} onClick={()=>goTo(p)}>{p}</button>)}</nav><a className="say-hello" href="mailto:merchantakshay94@gmail.com">Say hello <Arrow/></a></header>
      {page==="home"&&<section className="page home-page portrait-editorial">
        <div className="eyebrow"><span><i/> Born in one place, raised in a few, at home in all of them.</span></div>
        <div className="hero-grid"><div><h1>Akshay<br/>Merchant<span>.</span></h1></div><figure className="home-portrait"><img src="/profile.jpg" alt="Akshay Merchant"/></figure></div>
        <div className="home-links">
          <button onClick={()=>goTo("work")}><span>Work</span><b>01</b><p>I work at the intersection of data, technology and business—building useful systems that make complex decisions simpler.</p><Arrow/></button>
          <button onClick={()=>goTo("places")}><span>Places</span><b>02</b><p>Six cities, three continents and plenty of stories along the way.</p><Arrow/></button>
          <button onClick={()=>goTo("interests")}><span>Interests</span><b>03</b><p>The things I enjoy learning, playing and getting slightly obsessed with.</p><Arrow/></button>
          <button onClick={()=>goTo("socials")}><span>Socials</span><b>04</b><p>A few places to find my work, follow along or say hello.</p><Arrow/></button>
        </div>
        <footer className="mini-footer home-footer"><span>Luxembourg · <b>2026</b></span></footer>
      </section>}
      {page==="work"&&<section className="page work-page">
        <Intro num="01" name="Profile" title={<>Data. Insights.<br/>Impact.</>} copy="I work at the intersection of data, technology and business—building useful systems that make complex decisions simpler."/>
        <div className="stats kpi-ledger"><div><b>01</b><span className="kpi-icon"><KpiIcon name="people"/></span><strong>75+</strong><span className="kpi-label">interviews conducted</span></div><div><b>02</b><span className="kpi-icon"><KpiIcon name="savings"/></span><strong>$10.3M</strong><span className="kpi-label">annual savings delivered</span></div><div><b>03</b><span className="kpi-icon"><KpiIcon name="time"/></span><strong>11.5K+</strong><span className="kpi-label">annual hours repurposed</span></div><div><b>04</b><span className="kpi-icon"><KpiIcon name="quality"/></span><strong>99%</strong><span className="kpi-label">data quality improvement</span></div></div>
        <section className="work-section experience-section"><p className="kicker">Experience</p><div className="editorial-experience experience-unified">
          <article className="company-feature"><div className="company-heading"><div className="company-identity"><img src="/logo-amazon.png" alt="Amazon"/><div><span className="work-date">2019—Present</span><h2>Amazon</h2></div></div><div><p>Business Intelligence Engineer 2</p><span>USA · Luxembourg</span></div></div><div className="highlight-grid">{experienceHighlights.map(item=><div key={item.title}><b>{item.n}</b><p className="highlight-over">{item.title}</p><p>{item.copy}</p><strong>{item.impact}</strong></div>)}</div></article>
          <article className="company-feature company-secondary"><div className="company-heading"><div className="company-identity"><img src="/logo-pwc.png" alt="PricewaterhouseCoopers"/><div><span className="work-date">2018—2019</span><h2>PricewaterhouseCoopers</h2></div></div><div><p>Experienced Associate</p><span>Risk & Compliance · USA</span></div></div><div className="highlight-grid pwc-highlight"><div><b>04</b><p className="highlight-over">Protect</p><p>Built a transaction-monitoring framework that translated complex risk patterns into clear compliance decisions.</p><strong>$10M annual exposure reduction</strong></div></div></article>
        </div></section>
        <section className="work-section education-section"><p className="kicker">Education</p><div className="education-cards"><article><b>01</b><img src="/logo-lse-uniform.png" alt="London School of Economics"/><div className="education-meta"><time>2026—Present</time><span>UK</span></div><h3>AI Leadership</h3><p>London School of Economics</p></article><article><b>02</b><img src="/logo-uic-uniform.png" alt="University of Illinois Chicago"/><div className="education-meta"><time>2016—2018</time><span>USA</span></div><h3>MS Business Analytics</h3><p>University of Illinois Chicago</p></article><article><b>03</b><img src="/logo-mumbai-uniform.png" alt="University of Mumbai"/><div className="education-meta"><time>2012—2016</time><span>India</span></div><h3>BE Information Technology</h3><p>University of Mumbai</p></article></div></section>
        <section className="work-section expertise-section"><p className="kicker">Expertise</p><div className="capability-grid">{capabilities.map(item=><article key={item.title}><b>{item.n}</b><span>{item.over}</span><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div></section>
      </section>}
      {page==="places"&&<section className="page places-page">
        <Intro num="02" name="Places" title={<>A life in<br/>six coordinates.</>} copy="Six cities, three continents and plenty of stories along the way."/>
        <div className="places-layout"><div className="map-wrap"><svg className="world-map" viewBox="0 0 100 65" aria-label="Stylised map"><path d="M7 20 15 11l14 2 8 9-7 7-1 15-9 8-7-13-8-6Zm37-5 10-8 10 5 9-3 19 8-5 9 7 9-10 11-11-4-7 13-7-7-2-13-9-7Z"/><path className="route" d="M67 61C50 55 34 49 24 35S29 43 30.5 39S15 32 15 32C28 25 40 29 50 35"/>{places.map(p=><g key={p.id} className={`pin ${place===p.id?"selected":""}`} onClick={()=>setPlace(p.id)}><circle cx={p.x} cy={p.y} r="1.6"/><circle className="pulse" cx={p.x} cy={p.y} r="3.2"/></g>)}</svg><span className="map-caption">The route so far · 6 cities · 3 continents</span></div><div className="place-story"><div className="place-number">{String(places.findIndex(p=>p.id===place)+1).padStart(2,"0")}</div><p className="place-years">{selected.years}</p><h3>{selected.city}</h3><p>{selected.blurb}</p></div></div>
        <div className="city-buttons">{places.map(p=><button key={p.id} className={place===p.id?"active":""} onClick={()=>setPlace(p.id)}><i className="city-mark" aria-hidden="true">{cityMarks[p.id]}</i><span>{p.city}</span><small>{p.years}</small></button>)}</div>
      </section>}
      {page==="interests"&&<section className="page interests-page">
        <Intro num="03" name="Interests" title={<>Things that keep<br/>me curious.</>} copy="The things I enjoy learning, playing and getting slightly obsessed with."/>
        <div className="interest-grid">
          <Interest big over="Currently learning" title="How AI changes the way organisations make decisions." copy={["AI is getting increasingly good at answering questions, but I am more interested in what it means for the people asking them.","I recently began the AI Leadership program at the London School of Economics, where I am exploring how organizations can use AI to make better decisions, rethink how they work and turn exciting ideas into something genuinely useful."]} n="01"/>
          <Interest over="On the court" title="Tennis" copy={["I started learning tennis during my holiday back home, and somewhere between the questionable serves and very enthusiastic forehands, it slowly became my favorite sport.","I have now joined tennis school in Luxembourg to learn the craft properly—one Thursday evening, one rally and hopefully fewer balls into the net at a time."]} n="02"/>
          <Interest over="On the wrist" title="Watches" copy={["Every year, I promise myself that this will be the year I finally buy a watch. Then I decide to wait for a suitably memorable life event—and the search continues.","I am currently deciding between the Girard-Perregaux Laureato and the Rolex Land-Dweller, which would be easier if I were only comparing the watches and not every photograph, review and hypothetical future version of myself wearing them. The research continues. The budget suffers."]} n="03"/>
          <Interest over="In the water" title="Swimming" copy={["Gradually, swimming has gone from something I enjoyed to something I measure in increasingly ambitious 500m increments. My next target is 2kms, and I am already three-quarters of the way there—although the final 500m may have opinions of its own.","I have also conquered the flip turn, if “conquered” includes repeatedly getting water up my nose until it finally worked. Next, I want to swim the Défi de Monte-Cristo and discover whether countless pool lengths are enough preparation for a race named after an escaped prisoner."]} n="04"/>
          <Interest over="Out of my comfort zone" title="Chasing Adrenaline" copy={["Over the past few years, I have been finding increasingly creative ways to test my limits: skydiving in the Carolinas, the SkyJump in Vegas, cliff-jumping in Oregon and Mallorca, swimming with dolphins in Mauritius, and scuba-diving in Mallorca and Nice.","My highest cliff jump so far is 12m. I might go higher next time—provided I finally remember not to hit the water with my arms spread wide. Next on the list though is swimming with orcas in Norway, although a small part of me remains concerned that I may end up on their list too."]} n="05"/>
          <Interest over="On the Console" title="Gaming" copy={["I spend a perfectly unreasonable amount of time on my PlayStation, mostly exploring RPG worlds and becoming far too invested in the lives of fictional people.","I've played various games, but Uncharted will always be the series I come back to. Nathan Drake gets to travel the world, hunt for lost treasures and turn every quiet archaeological expedition into complete chaos—which is a fairly convincing formula for a perfect game."]} n="06"/>
          <Interest big over="Calculated Optimism" title="Investing" copy={["I started investing at 18, and my portfolio has followed me from India to the US and Europe—occasionally growing, occasionally panicking and generally experiencing the full emotional range of international markets. Moving between countries has also given me an excuse to explore different businesses, economies and ways of investing.","Technically, I invest across equities, fixed income and cash. Realistically, equities receive most of my attention because I enjoy researching companies, understanding how they make money and convincing myself that every market dip is an exciting buying opportunity. I am investing with the hope that time, compounding and one or two spectacularly lucky decisions will eventually make “millionaire” less of an ambition and more of a description."]} n="07"/>
        </div>
      </section>}
      {page==="socials"&&<section className="page social-page">
        <Intro num="04" name="Socials" title={<>Find me<br/>elsewhere.</>} copy="A few places to find my work, follow along or say hello."/>
        <div className="social-card-layout"><div className="social-card-note"><p className="kicker">Say hello</p><span className="social-note-icon"><SocialIcon name="email"/></span><h3>The internet is better with good conversations.</h3><a href="mailto:merchantakshay94@gmail.com">Email me <Arrow/></a></div><div className="social-cards">{socialLinks.map((item,index)=><a key={item.name} href={item.href} target="_blank" rel="noreferrer"><span>{String(index+1).padStart(2,"0")}</span><span className="social-card-icon"><SocialIcon name={item.icon}/></span><h3>{item.name}</h3><p>{item.note}</p><Arrow/></a>)}</div></div>
      </section>}
    </div>
  </main>;
}
function Intro({num,name,title,copy}:{num:string,name:string,title:React.ReactNode,copy?:string}){return <div className="page-intro"><p className="kicker"><span className="section-num">{num}</span> / {name}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function Interest({big,over,title,copy,n}:{big?:boolean,over:string,title:string,copy:string|string[],n:string}){return <article className={`${big?"interest-feature ":""}${Array.isArray(copy)?"interest-copy-long":""}`}><span>{over}</span><h3>{title}</h3>{Array.isArray(copy)?copy.map((paragraph,index)=><p key={index}>{paragraph}</p>):<p>{copy}</p>}<b>{n}</b></article>}
